from __future__ import annotations


FILE_MAGIC = 0xA5E0
FRAME_MAGIC = 0xF1FA

FILE_HEADER_SIZE = 128
FRAME_HEADER_SIZE = 16
CHUNK_HEADER_SIZE = 6

COLOR_DEPTH_INDEXED = 8
COLOR_DEPTH_GRAYSCALE = 16
COLOR_DEPTH_RGBA = 32
SUPPORTED_COLOR_DEPTHS = {COLOR_DEPTH_INDEXED, COLOR_DEPTH_GRAYSCALE, COLOR_DEPTH_RGBA}

CHUNK_LAYER = 0x2004
CHUNK_CEL = 0x2005
CHUNK_TAGS = 0x2018
CHUNK_PALETTE = 0x2019

CEL_RAW_IMAGE = 0
CEL_LINKED = 1
CEL_COMPRESSED_IMAGE = 2
CEL_COMPRESSED_TILEMAP = 3
